---
- name: "Automate running docker container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop zero-to-hero-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm zero-to-hero-container
      ignore_errors: yes

    - name: remove used image
      command: docker rmi zero-to-hero-img
      ignore_errors: yes

    - name: build docker image from dockerfile
      command: docker build -t zero-to-hero-img .

    - name: create tag to image
      command: docker tag zero-to-hero-img triple3a/zero-to-hero

    - name: push image to dockerhub
      command: docker push triple3a/zero-to-hero

    - name: run container from image
      command: docker run -d --name zero-to-hero-container -p 5000:5000 zero-to-hero-img